sonar.projectKey=fiberline-crm
sonar.projectName=Fiberline CRM
sonar.projectVersion=1.0
sonar.sources=.
sonar.exclusions=**/.scannerwork/**
sonar.host.url=https://sonarcloud.io
sonar.organization=pscyber-co-ltd
